version: "3.8"

services:

  db:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  backend:
    ports:
      - "${BACKEND_PORT:-3001}:3001"

  frontend:
    ports:
      - "${FRONTEND_PORT:-3000}:3000"