import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1787025033136 implements MigrationInterface {
    name = 'InitialSchema1787025033136'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'hr-staff', 'user')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "profileComplete" boolean NOT NULL DEFAULT false, "isSupervisor" boolean NOT NULL DEFAULT false, "firstName" character varying, "lastName" character varying, "middleInitial" character varying, "campus" character varying, "officeAffiliation" character varying, "collegeOfficeUnit" character varying, "collegeProgram" character varying, "personnelType" character varying, "educAttainment" character varying, "educAttainmentSpec" character varying, "currentPosition" character varying, "designation" character varying, "yearsInPosition" double precision, "yearsInCSU" double precision, "supervisorLastName" character varying, "supervisorFirstName" character varying, "supervisorMiddleInitial" character varying, "supervisorEmail" character varying, "office" character varying, "headOfUnit" character varying, "headLastName" character varying, "headFirstName" character varying, "headMiddleInitial" character varying, "raterName" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lna_submissions" ("id" SERIAL NOT NULL, "refId" character varying NOT NULL, "userId" uuid, "submitterEmail" character varying, "campus" character varying, "officeAffiliation" character varying, "office" character varying, "collegeProgram" character varying, "headOfUnit" character varying, "position" character varying, "designation" character varying, "datePrepared" character varying, "yearCovered" character varying, "totalPersonnel" character varying, "purpose" character varying, "workforceProfile" jsonb, "coreCompetencies" jsonb, "leadershipComps" jsonb, "orgComps" jsonb, "technicalComps" jsonb, "clusterSummaryRaw" jsonb, "dataSourcesRaw" jsonb, "dataSourceInsights" jsonb, "leadInterventions" jsonb, "submittedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8caaa3d4847f7eae29760e2a779" UNIQUE ("refId"), CONSTRAINT "PK_a75ed70d5ea85c047dfe9d61b30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "idp" ("id" SERIAL NOT NULL, "refId" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "userId" uuid, "employeeEmail" character varying, "campus" character varying, "officeAffiliation" character varying, "collegeOfficeUnit" character varying, "collegeProgram" character varying, "nameOfPersonnel" character varying, "lastName" character varying, "firstName" character varying, "middleInitial" character varying, "educAttainment" character varying, "educAttainmentSpec" character varying, "currentPosition" character varying, "designation" character varying, "yearsInPosition" double precision, "yearsInCSU" double precision, "supervisorName" character varying, "supervisorEmail" character varying, "headerPurpose" character varying, "competencyPurpose" character varying, "competencyRowsJson" text, "agapRowsJson" text, "proactRowsJson" text, "supervisorRemarks" character varying, "supervisorApproval" character varying, "supervisorSignedAt" character varying, "supervisorAssessment" text, "supervisorToken" character varying, "supervisorNotifiedAt" character varying, "submittedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_da3a6f2bbce6326703dd1495a2a" UNIQUE ("refId"), CONSTRAINT "UQ_b4c8e87eda789e4337247c9b1bb" UNIQUE ("supervisorToken"), CONSTRAINT "PK_5273f95b53e942efb5bd0f2e746" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "idp_field_suggestions" ("id" SERIAL NOT NULL, "field_name" character varying(50) NOT NULL, "value" text NOT NULL, "used_count" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c61536cb1ddeb99acc33face181" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL, "token" character varying NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ab673f0e63eac966762155508ee" UNIQUE ("token"), CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "lna_submissions" ADD CONSTRAINT "FK_83c7322fb41fbe42c23b85a5be9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "idp" ADD CONSTRAINT "FK_4cfc06835de51615af8d847fd12" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "idp" DROP CONSTRAINT "FK_4cfc06835de51615af8d847fd12"`);
        await queryRunner.query(`ALTER TABLE "lna_submissions" DROP CONSTRAINT "FK_83c7322fb41fbe42c23b85a5be9"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "idp_field_suggestions"`);
        await queryRunner.query(`DROP TABLE "idp"`);
        await queryRunner.query(`DROP TABLE "lna_submissions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
